wandb_version: 1

model:
  desc: null
  value: lr
dataset:
  desc: null
  value: mnist
data_dir:
  desc: null
  value: ./../../../data/mnist
spar_ratio:
  desc: null
  value: 0.02
partition_method:
  desc: null
  value: hetero
batch_size:
  desc: null
  value: 20
client_optimizer:
  desc: null
  value: sgd
lr:
  desc: null
  value: 0.1
wd:
  desc: null
  value: 0.0
epochs:
  desc: null
  value: 5
client_num_in_total:
  desc: null
  value: 28
client_num_per_round:
  desc: null
  value: 28
comm_round:
  desc: null
  value: 50
frequency_of_the_test:
  desc: null
  value: 1
gpu:
  desc: null
  value: 1
ci:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714128106.0
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.7
      5: 0.16.5
      8:
      - 5
      13: linux-x86_64
